### PR TITLE
Fix by using cleverbot.io now

### PR DESCRIPTION
**Pull request by manicholls**

### CODE REVIEW

**Comment by jsandova** [comment]
I made the changes to the files, however when I attempt to start Lita I get the following error. Even after I ran a gem install cleverbot.

root@bot:/home/roboto# lita start &
[1] 3072
root@bot:/home/roboto# /var/lib/gems/2.2.0/gems/lita-ai-0.1.1/lib/lita-ai.rb:2:in `require': cannot load such file -- cleverbot (LoadError)
    from /var/lib/gems/2.2.0/gems/lita-ai-0.1.1/lib/lita-ai.rb:2:in`<top (required)>'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in`block (2 levels) in require'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in`block in require'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in`require'
    from /var/lib/gems/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
    from /var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/cli.rb:61:in`start'
    from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
    from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from /var/lib/gems/2.2.0/gems/lita-4.7.0/bin/lita:6:in `<top (required)>'
    from /usr/local/bin/lita:23:in`load'

**Comment by manicholls** [comment]
Make sure the gem you install is 'cleverbot_io'.  I found it a bit confusing that the gem is named differently than the require statement, but those are the instructions i found at https://cleverbot.io/

You might also need to add 'gem "cleverbot_io"' to your Gemfile for Lita.

**Comment by jsandova** [comment]
Many thanks Manicholls, after installing the cleverbot_io gem and adding it to my gem file it worked. I really appreciate the help.

**Comment by tombeynon** [comment]
@manicholls Thank you for doing this, and I'm sorry it's taken me so long to merge it. Looks great, and I think cleverbot.io is the best way to go moving forward.

**Comment by tombeynon** [comment]
Closing in favour of #7

**Pull request closed without merging**
